### ISSUE TITLE
g:nf_loop_filesのちょっとかしこいバージョン

### ISSUE THREAD

**Issue by tyru** [tyru/nextfile.vim#1]
https://twitter.com/thinca/status/219453939375026179

> 常にループして欲しいわけじゃなくて、端まで行ったことをバッファが切り替わらないことによって確認してから改めてループさせたい。イメージとしてはキーリピートでのスクロールで端で一旦止まるけど再度押すとループする感じ。もちろんVimではキーリピートの判定は無理なので手動で。

**Comment by tyru** [comment]
@thinca 状態を持つのが嫌だったので、ちょっと違ったものになりましたがどうでしょうか？>`g:nf_loop_hook_fn`

以下は`g:nf_loop_hook_fn`の使用例です。
注意点としては、`g:nf_loop_files`が1でないと使えません。
`NFLoopMsg()`はVimの`n`や`N`コマンドみたく、wrap aroundするとメッセージを出します。
`NFLoopPrompt()`はユーザにプロンプトを出して、yesでなければファイルを開くのをやめます。

```
function! NFLoopMsg(file_to_open)
    echohl WarningMsg
    echom 'open a file from the start...'
    echohl None
    " Always open a next/previous file...
    return 1
endfunction
function! NFLoopPrompt(file_to_open)
    return input('open a file from the start? [y/n]:') =~? 'y\%[es]'
endfunction

" g:nf_loop_hook_fn only works when g:nf_loop_files is true.
let g:nf_loop_files = 1
" Call this function when wrap around.
" let g:nf_loop_hook_fn = 'NFLoopPrompt'
let g:nf_loop_hook_fn = 'NFLoopMsg'
" To avoid |hit-enter| for NFLoopMsg().
let g:nf_open_command = 'silent edit'
```

**Comment by thinca** [comment]
想定していたのとは違いますが、なんとかできないかやってみますー。

**Comment by tyru** [comment]
@thinca 叩き台みたいなものだし、ブランチ切ってあるので、自由に意見やコード出してくれて構わないです。

**Comment by thinca** [comment]
今更ですが問題なさそうです！

**Comment by tyru** [comment]
了解です。ありがとうございました！

**Comment by thinca** [comment]
ちなみにこれ私は閉じれないですが閉じちゃって大丈夫です！

**Comment by tyru** [comment]
あ、そうでした。ありがとうございます！
