### ISSUE TITLE
現在のバッファのファイルが削除されていても動いて欲しい

### ISSUE THREAD

**Issue by thinca** [tyru/nextfile.vim#2]
個人的な使い方の問題になってしまうのですが、`nextfile.vim` を使いつつカレントバッファのファイルを削除することがよくあります。
ファイルを削除すると `nextfile.vim` はまた先頭からファイルを表示してしまうのですが、カレントバッファのファイルが存在するように次のファイルを表示してくれると嬉しいです。

例:

```
A.txt
B.txt
C.txt
```

と言うファイルがある場合に

```
:edit B.txt
```

とした後、

```
:call delete(expand('%:p'))
```

として、

```
<Leader>n
```

で次のファイルに移動する際に、現在は `A.txt` が開かれるが、`C.txt` が開かれて欲しい。

**Comment by tyru** [comment]
確かにこの挙動には自分もちょっと疑問に思っていたので、 @thinca さんの案で解決できそうです。
平日は時間あるか分からないのでいつ取り掛かれるか分からないですが、ちょっと実装してみます。

**Comment by tyru** [comment]
これ、現在のバッファだけでいいのか、それとも（すでに削除されていても）バッファリストにある全てのファイル名どちらがいいのか、ちょっと迷ったんですが、とりあえず @thinca さんの提案通り現在のバッファのみで実装しました。
現在のバッファは実際に見えてるので今回のPRのように直感的でない挙動のように感じますが、バッファリストにある全てのファイル名だと、削除したファイルが見えないバッファリストにあるために突然開かれるので、そっちの方が直感的でないように感じたので。
変更は難しくはないですが、@thincaさんはどちらがいいと思いますか？

**Comment by thinca** [comment]
動作は私としてはカレントバッファだけで大丈夫です。
ただ、実装がちょっとまずいようです。カレントバッファがカレントディレクトリに存在する場合にしか動かないようです。 `curbuf_is_on_same_dir` のチェックは不要ではないでしょうか?

**Comment by tyru** [comment]
あーなるほど…不要ですね。ありがとうございます。
修正しました！

**Comment by thinca** [comment]
Nice! :+1: 
ありがとうございました！

**Comment by tyru** [comment]
こちらこそどうもです。:relieved:
